name: Build and Deploy
on:
  push:
    branches: [master]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Add channel ID
        run: sed -i s/YOUR-CHANNEL-ID/XB7ugFZvx2dYbkvj/g ./src/App.vue
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install packages
        run: npm ci
      - name: Build app
        run: npm run build && touch ./dist/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.
